version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: youtube_scheduler_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: youtube_scheduler
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - youtube_network

  backend:
    build: ./backend
    container_name: youtube_scheduler_backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=youtube_scheduler
      - CORS_ORIGINS=https://live.happyfying.com,http://localhost:3000
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - youtube_network

  frontend:
    build: ./frontend
    container_name: youtube_scheduler_frontend
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=https://live.happyfying.com
    ports:
      - "3000:3000"
    networks:
      - youtube_network

  nginx:
    image: nginx:alpine
    container_name: youtube_scheduler_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - youtube_network

volumes:
  mongodb_data:

networks:
  youtube_network:
    driver: bridge